// Generated by upstream's CMake build (see modules/ts/CMakeLists.txt) from
// CMAKE_INSTALL_PREFIX and OPENCV_TEST_DATA_INSTALL_PATH, both unset here,
// so upstream's own build would produce this same empty file.
