using autoconf

intf_libs = # Interface dependencies.

h{version_string.inc}: extension = inc
lib{opencv-config}: {h}{cvconfig cv_cpu_config} \
  {hxx}{custom_hal opencv_data_config} \
  {h}{version_string.inc} \
  opencv2/{hxx}{opencv_modules}

h{cvconfig}: in{cvconfig}
{
    autoconf.flavor = cmake
    BUILD_SHARED_LIBS = false
    CV_ENABLE_INTRINSICS = false
    CV_DISABLE_OPTIMIZATION  = false
    CUDA_ARCH_BIN = ""
    CUDA_ARCH_FEATURES = ""
    CUDA_ARCH_PTX = ""
    HAVE_CLAMDBLAS  = false 
    HAVE_CLAMDFFT  = false 
    HAVE_CLP  = false 
    HAVE_CUDA  = false 
    HAVE_CUBLAS  = false 
    HAVE_CUDNN  = false 
    HAVE_CUFFT  = false 
    HAVE_DIRECTX = false 
    HAVE_DIRECTX_NV12 = false 
    HAVE_D3D11 = false 
    HAVE_D3D10 = false 
    HAVE_D3D9 = false 
    HAVE_EIGEN = false 
    HAVE_GDAL  = false 
    HAVE_HALIDE  = false 
    HAVE_VULKAN  = false 
    HAVE_INTTYPES_H  = false 
    HAVE_IPP  = false 
    HAVE_IPP_ICV  = false 
    HAVE_IPP_IW  = false 
    HAVE_IPP_IW_LL  = false 
    HAVE_OPENJPEG  = false 
    HAVE_JASPER  = false 
    HAVE_AVIF = false
    HAVE_JPEG = false 
    HAVE_LIBPNG_PNG_H  = false 
    HAVE_GDCM  = false 
    HAVE_NVCUVID  = false 
    HAVE_NVCUVID_HEADER  = false 
    HAVE_DYNLINK_NVCUVID_HEADER  = false 
    HAVE_NVCUVENC  = false 
    HAVE_OPENCL = false 
    HAVE_OPENCL_STATIC  = false 
    HAVE_OPENCL_SVM  = false 
    HAVE_OPENCL_D3D11_NV = false 
    HAVE_OPENEXR  = false 
    HAVE_OPENGL  = false 
    HAVE_PNG = false
    HAVE_SPNG  = false 
    HAVE_PTHREAD  = false 
    HAVE_PTHREADS_PF  = false 
    HAVE_TBB  = false 
    HAVE_HPX  = false 
    HAVE_TIFF  = false 
    WORDS_BIGENDIAN  = false 
    HAVE_VA  = false 
    HAVE_VA_INTEL  = false 
    HAVE_LAPACK  = false 
    ENABLE_INSTRUMENTATION  = false 
    HAVE_OPENVX  = false 
    OPENCV_TRACE = false 
    HAVE_QUIRC  = false 
}

temp_cpu_empty_baseline_definitions = "#define CV_CPU_BASELINE_FEATURES 0"
temp_cpu_empty_dispatch_definitions = "#define CV_CPU_DISPATCH_FEATURES 0"
h{cv_cpu_config}: in{cv_cpu_config}
{
  OPENCV_CPU_BASELINE_DEFINITIONS_CONFIGMAKE = $temp_cpu_empty_baseline_definitions
  OPENCV_CPU_DISPATCH_DEFINITIONS_CONFIGMAKE = $temp_cpu_empty_dispatch_definitions
}

temp_hal_empty = ""
hxx{custom_hal}: in{custom_hal.hpp.in}
{
  autoconf.substitutions = _hal_includes@$temp_hal_empty
}

# TODO: Check if the defines in this files are actually used anywhere outside CMake
hxx{opencv_data_config}: in{opencv_data_config.hpp.in}
{
}

h{version_string.inc}: in{version_string}

opencv2/hxx{opencv_modules}: in{opencv_modules.hpp.in}
{
  autoconf.flavor = cmake
  OPENCV_ENABLE_NONFREE = false
  OPENCV_MODULE_DEFINITIONS_CONFIGMAKE = ""
}

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{opencv-config}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install recreating subdirectories.
#
{h}{*}:
{
  install         = include/
  install.subdirs = true
}

{hxx cxx}{*}:
{
  install         = include/
  install.subdirs = true
}
